---
--- Generated by Luanalysis
--- Created by selen.
--- DateTime: 12/7/2023 8:12 PM
---
function event(args)

    local test = args.test
    local test2 = args.test2
    local event = args.event
    print(test)
    print(test2)

    if event ~= nil then
        local eventName = event:getEventName()
        if (eventName == "PlayerJoinEvent") then
            print("Player Join Test Passed")
        end
    else
        print("Player Join Test Failed Successfully")
    end

end

function run(args)
    local test = args.test
    local test2 = args.test2

    print(test)
    print(test2)
end

return {
    event = event,
    run = run
}